/**
 * Wix CLI Data Collections Extension
 * 
 * Defines the TermsOfUse collection for hierarchical Terms of Use management.
 * Supports arbitrary nesting depth with parent-child relationships.
 * 
 * System fields (automatic):
 * - _id: unique identifier (generated by system)
 * - _createdDate: ISO datetime (auto set at creation)
 * - _updatedDate: ISO datetime (auto updated on changes)
 * - _owner: user who owns the item
 */

import { extensions } from '@wix/astro/builders';

export const dataExtension = extensions.genericExtension({
  // IMPORTANT: Replace with a freshly generated UUID v4 string
  // Format: xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
  compId: '6a7f8c9d-2e3b-4f1a-9c8b-7d6e5f4a3b2c',
  
  compName: 'data-extension',
  compType: 'DATA_COMPONENT',
  
  compData: {
    dataComponent: {
      collections: [
        {
          schemaUrl: 'https://www.wix.com/',
          
          // Collection ID (will be scoped with app namespace)
          idSuffix: 'terms-of-use',
          
          // Display name in CMS
          displayName: 'Terms of Use',
          
          // Field used when referencing items
          displayField: 'title',
          
          fields: [
            {
              key: 'id',
              displayName: 'Unique Identifier',
              type: 'TEXT',
              required: true,
              unique: true,
              description: 'Unique identifier for this section (e.g., "section-1", "intro")'
            },
            {
              key: 'level',
              displayName: 'Hierarchy Level',
              type: 'NUMBER',
              required: true,
              defaultValue: 1,
              description: 'Nesting level: 1 (main section), 2 (subsection), 3+ (nested content)'
            },
            {
              key: 'parentId',
              displayName: 'Parent Section ID',
              type: 'TEXT',
              description: 'ID of parent section - empty for level 1 sections. Used to build hierarchy.'
            },
            {
              key: 'title',
              displayName: 'Section Title',
              type: 'TEXT',
              required: true,
              description: 'Title of this section or subsection'
            },
            {
              key: 'content',
              displayName: 'Content',
              type: 'RICH_TEXT',
              description: 'HTML/rich text content for this section, supports formatting'
            },
            {
              key: 'order',
              displayName: 'Display Order',
              type: 'NUMBER',
              required: true,
              defaultValue: 0,
              description: 'Sort order within parent section (0, 1, 2, ...)'
            },
            {
              key: 'isOpen',
              displayName: 'Initially Open',
              type: 'BOOLEAN',
              defaultValue: false,
              description: 'If true, section expands by default in UI; false collapses it'
            },
            {
              key: 'type',
              displayName: 'Content Type',
              type: 'TEXT',
              required: true,
              defaultValue: 'section',
              description: 'Type of content: "section" (expandable), "list" (bullet points), "paragraph" (text block)'
            },
            {
              key: 'metadata',
              displayName: 'Custom Metadata',
              type: 'ANY',
              description: 'Flexible JSON object for custom data (tags, categories, version info, etc.)'
            }
          ],
          
          // Permissions: public read for site, admin write for dashboard
          dataPermissions: {
            // Public read access
            itemRead: 'ANYONE',
            // Admin/privilege users only for create
            itemInsert: 'PRIVILEGED',
            // Admin/privilege users only for update
            itemUpdate: 'PRIVILEGED',
            // Admin/privilege users only for delete
            itemRemove: 'PRIVILEGED'
          },
          
          // Optional: Example initial data
          initialData: [
            {
              id: 'intro',
              level: 1,
              parentId: '',
              title: 'Introduction',
              content: '<p>Welcome to our Terms of Use. Please read carefully.</p>',
              order: 0,
              isOpen: true,
              type: 'paragraph',
              metadata: { version: '1.0', status: 'published' }
            },
            {
              id: 'section-1',
              level: 1,
              parentId: '',
              title: 'Section 1: User Agreement',
              content: '<p>By using this service, you agree to these terms.</p>',
              order: 1,
              isOpen: false,
              type: 'section',
              metadata: { version: '1.0' }
            },
            {
              id: 'section-1-subsection-1',
              level: 2,
              parentId: 'section-1',
              title: '1.1 Eligibility',
              content: '<ul><li>You must be at least 18 years old</li><li>You must have a valid account</li></ul>',
              order: 0,
              isOpen: false,
              type: 'list',
              metadata: { version: '1.0' }
            },
            {
              id: 'section-2',
              level: 1,
              parentId: '',
              title: 'Section 2: Limitations',
              content: '<p>The service is provided as-is without warranties.</p>',
              order: 2,
              isOpen: false,
              type: 'section',
              metadata: { version: '1.0' }
            }
          ]
        }
      ]
    }
  }
});
